### ISSUE TITLE
Wrong handling of bam-files, containing hard clipped reads

### ISSUE THREAD

**Issue by 1dayac** [vpc-ccg/pamir#2]
Hello, guys!
I recently found that your code that process bam files back to fasta produces incorrect results. In general, if CIGAR-string of alignment contains 'H' (basically it means that read is contained in multiple bam-records) you output separate read for each of this record. So fasta file looks like

>1
ACGTACGT
>2
ACCT
>2 
GATT
>3
etc...
0

BTW, what are your running time estimates for 100-Gb gzipped fasta file?

Best, 
Dmitrii Meleshko

**Comment by yenyilin** [comment]
Hi Dmitrii,

Thanks for the feedback. 

(1) I see. I will fix this part as soon as possible. 

(2)  On a 96-cpu 2.60GHz Xeon(R) E7-4860 v2 machine, it took pamir around 2100 mins (real time) to finish the dataset with parameters  --mrsfast-n 50  --num-worker 72 --mrsfast-min 300 --mrsfast-max 600 --donot-remove-contaminant. I don't keep extac user system time but that should be around 14000 mins.

 Please let us know for any further questions.

**Comment by 1dayac** [comment]
Great, I was happy to help!
Probably, I specified low number of threads, I had a problem with mrsfast worked for one week and didn't finished in a week
Thank you

**Comment by yenyilin** [comment]
Hi Dmitrii,

Can you share your parameter with us?

Thank!

**Comment by yenyilin** [comment]
Hi Dmitrii,

Sorry for late response. v1.2.2 now would only extract exact number of reads regardless of secondary or multiple mappings in the provided SAM/BAM file.

Thanks.
