### ISSUE TITLE
InputFunctionException 

### ISSUE THREAD

**Issue by christinafliege** [vpc-ccg/pamir#40]
I'm getting the following python error when attempting to run pamir.  Thanks!

InputFunctionException in line 1424 of path/to/Snakefile:
KeyError: 'DataFilePartialName'
Wildcards:
sample=DataFilePartialName

**Comment by f0t1h** [comment]
Can you please post the config file you've used and full log of the failed run.

**Comment by christinafliege** [comment]
Thank you, my config file is:

path:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir
raw-data:
  /matt_k_inputs
reference:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/Basilexamples/ref.1.fa
population:
  basilexamp
input:
  "basil":
  - Basilexamps.bam
centromeres:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/centromeres.txt

The full error file is:

/usr/local/apps/bioapps/python/Python-3.6.1/bin/snakemake
... Exists :)
/usr/local/apps/bioapps/samtools/samtools-1.9/samtools
... Exists :)
/usr/local/apps/bioapps/bedtools/bedtools-2.28.0/bin/bedtools
... Exists :)
/usr/local/apps/bioapps/mrsfast/mrsfast-3.4.1//mrsfast
... Exists :)
/usr/local/apps/bioapps/bwa/bwa-0.7.17-compiler_intel-16.0/bwa
... Exists :)
Snakemake version...OK
Samtools version...OK
MrsFAST version...OK
Bedtools version...OK
Building DAG of jobs...
InputFunctionException in line 1424 of /usr/local/apps/bioapps/pamir/pamir/pamir/Snakefile:
KeyError: 'Basilexamps'
Wildcards:
sample=Basilexamps

Additionally,  when I remove the slash before the raw data field in the config file I get the following error file:

/usr/local/apps/bioapps/python/Python-3.6.1/bin/snakemake
... Exists :)
/usr/local/apps/bioapps/samtools/samtools-1.9/samtools
... Exists :)
/usr/local/apps/bioapps/bedtools/bedtools-2.28.0/bin/bedtools
... Exists :)
/usr/local/apps/bioapps/mrsfast/mrsfast-3.4.1//mrsfast
... Exists :)
/usr/local/apps/bioapps/bwa/bwa-0.7.17-compiler_intel-16.0/bwa
... Exists :)
Snakemake version...OK
Samtools version...OK
MrsFAST version...OK
Bedtools version...OK
Building DAG of jobs...
MissingInputException in line 1344 of /usr/local/apps/bioapps/pamir/pamir/pamir/Snakefile:
Missing input files for rule link_bam:
/projects/mgc/Project_2/HLHS_BasilAniseVC/Pamirmatt_k_inputs/Basilexamps.bam

**Comment by f0t1h** [comment]
We added bam support and many other updates to pamir with 2.1.0 release. Can you try again with a clean install of the 2.1.0? You can also see the small example in the README.

**Comment by mortunco** [comment]
Dear @christinafliege,

Could you use insert your config.yaml or output from the command line in to \``` hello \``` so it wont be formatted by markdown?

for ex:
```
hello
```
Thanks.

**Comment by christinafliege** [comment]
'''path:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir
raw-data:
  /matt_k_inputs
reference:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/Basilexamples/ref.1.fa
population:
  basilexamp
input:
  "basil":
  - Basilexamps.bam
centromeres:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/centromeres.txt'''

**Comment by christinafliege** [comment]
'''path:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir
raw-data:
  /matt_k_inputs
reference:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/Basilexamples/ref.1.fa
population:
  basilexamp
input:
  "basil":
  - Basilexamps.bam
centromeres:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/centromeres.txt'''

**Comment by christinafliege** [comment]
```path:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir
raw-data:
  /matt_k_inputs
reference:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/Basilexamples/ref.1.fa
population:
  basilexamp
input:
  "basil":
  - Basilexamps.bam
centromeres:
  /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/inputs/centromeres.txt


/usr/local/apps/bioapps/python/Python-3.6.1/bin/snakemake
... Exists :)
/usr/local/apps/bioapps/samtools/samtools-1.9/samtools
... Exists :)
/usr/local/apps/bioapps/bedtools/bedtools-2.28.0/bin/bedtools
... Exists :)
/usr/local/apps/bioapps/mrsfast/mrsfast-3.4.1//mrsfast
... Exists :)
/usr/local/apps/bioapps/bwa/bwa-0.7.17-compiler_intel-16.0/bwa
... Exists :)
Snakemake version...OK
Samtools version...OK
MrsFAST version...OK
Bedtools version...OK
Building DAG of jobs...
InputFunctionException in line 1424 of /usr/local/apps/bioapps/pamir/pamir/pamir/Snakefile:
KeyError: 'Basilexamps'
Wildcards:
sample=Basilexamps

**Comment by christinafliege** [comment]
> We added bam support and many other updates to pamir with 2.1.0 release. Can you try again with a clean install of the 2.1.0? You can also see the small example in the README.

we are currently running 5.17 which was freshly installed for this project.  Thanks!

**Comment by f0t1h** [comment]
I mean the pamir version.

**Comment by joshfactorial** [comment]
I'm one of the people who installed Pamir for Christina. I found version 2.1.0 and will try a fresh install.

**Comment by joshfactorial** [comment]
Right, so I found version 2.1.0 in releases, downloaded it to our cluster, extracted and ran ```make``` and got the following:
```
$ make 
make[1]: Entering directory '/usr/local/apps/bioapps/pamir/pamir-2.1.0'
Please clone the repository with --recursive option!
Makefile:114: recipe for target 'ext/edlib/edlib/include/edlib.h' failed
make[1]: *** [ext/edlib/edlib/include/edlib.h] Error 1
make[1]: Leaving directory '/usr/local/apps/bioapps/pamir/pamir-2.1.0'
Makefile:60: recipe for target 'release' failed
make: *** [release] Error 2
```
Originally I just cloned the repo and did it that way. I tried looking for ext/edlib/edlib/include/edlib.h and it does not appear to be present

**Comment by fhach** [comment]
I assume you downloaded the tarball. 
Please clone recursively so it can download its submodules. `2.1.0` is currently master but you can easily add it to recursive command.

```
git clone https://github.com/vpc-ccg/pamir.git --branch 2.1.0 --recursive
```

**Comment by joshfactorial** [comment]
I reinstalled using ```git clone https://github.com/vpc-ccg/pamir.git --branch 2.1.0 --recursive``` and it is still giving is the InputFunctionException error.

**Comment by f0t1h** [comment]
Can you confirm the input bam exists at the path:
```
 /projects/mgc/Project_2/HLHS_BasilAniseVC/Pamir/matt_k_inputs/Basilexamps.bam
```

**Comment by joshfactorial** [comment]
Yes, that is the location and ```samtools view``` shows that it has reads.

**Comment by f0t1h** [comment]
Can you post the latest error log?

**Comment by joshfactorial** [comment]
```
/usr/local/apps/bioapps/python/Python-3.6.1/bin/snakemake
... Exists :)
/usr/local/apps/bioapps/samtools/samtools-1.9/samtools
... Exists :)
/usr/local/apps/bioapps/bedtools/bedtools-2.28.0/bin/bedtools
... Exists :)
/usr/local/apps/bioapps/mrsfast/mrsfast-3.4.1//mrsfast
... Exists :)
/usr/local/apps/bioapps/bwa/bwa-0.7.17-compiler_intel-16.0/bwa
... Exists :)
Snakemake version...OK
Samtools version...OK
MrsFAST version...OK
Bedtools version...OK
Building DAG of jobs...
InputFunctionException in line 1428 of /usr/local/apps/bioapps/pamir/pamir-2.1.0/pamir/Snakefile:
KeyError: 'Basilexamps'
Wildcards:
sample=Basilexamps
```

**Comment by fhach** [comment]
I think we managed to replicate the error and we narrowed down it to the following line. Can you please replace this in your config file. We would like to verify this while we fixing the code to work with your original config file.
```
input:
  "Basilexamps":
    - Basilexamps.bam
```

**Comment by fhach** [comment]
@joshfactorial any update on this? We have a fix on our dev branch that we would like to merge to master to address this issue more broadly. I would like to confirm that this config line was causing the crash.

**Comment by christinafliege** [comment]
When we changed the config file inputs like above it appeared to start working, however then we ran into other issues.  It does appear that this is correct and this input change fixed that issue.

**Comment by fhach** [comment]
That is good. We will merge the new snakemake rules into the master branch today. Please open up another issue with your log and we can quickly check it out.  We will close this issue upon merging to master.

**Comment by joshfactorial** [comment]
We're making progress now on troubleshooting. Will post if we hit any other roadblocks. Thanks for the help!
