### ISSUE TITLE
Pamir.sh requiring centromer parameter is inconsistent with README

### ISSUE THREAD

**Issue by Krannich479** [vpc-ccg/pamir#46]
Hi, 
I am using your latest pamir.sh (*commit f49e0b8795a47e640eee7307fe6eaa7c0b690964, of May 29th 2020*) as follows:
`
/path/to/pamir/pamir.sh --configfile /path/to/config.yaml -j 16
`
and receive an error about the centromer parameter:
```
Running Pamir (f49e0b8)
snakemake(5.9.1)... OK 
samtools(1.9)... OK 
bedtools(2.29.2)... OK 
mrsfast(3.4.1)... OK 
bwa(0.7.17)... OK 
repeatmasker(4.0.9)... OK, Version not checked.
AssertionError in line 7 of /path/to/pamir/pamir/Snakefile:
centromeres is a mandatory field in config
  File "/path/to/pamir/pamir/Snakefile", line 25, in <module>
  File "/path/to/pamir/pamir/Snakefile", line 7, in cfg_mandatory
```

According to your README, the centromer parameter is not mandatory and I also prefer not to exclude regions. Is this possibly just an easy fix of un-setting a *mandatory* flag somewhere?

**Comment by fhach** [comment]
@Krannich479 it should be addressed today.

**Comment by fhach** [comment]
@Krannich479 You may check the master branch. 
`make clean && make`

**Comment by Krannich479** [comment]
That seems solved to me. Thanks!
