### ISSUE TITLE
mrsfast mapping min/max

### ISSUE THREAD

**Issue by calkan** [vpc-ccg/pamir#9]
Most of the time the # of reads is not sufficient for mrsfast to determine min/max values. When the input is BAM/CRAM, just use the first ~100K lines in the input and calculate min/max. Then pass these values to mrsfast @yenyilin @fhach

**Comment by fhach** [comment]
Fixed. Calculated from original bam/sam/cram during the processing. @f0t1h, please reference this issue during merge of 2.0.0.
